// Mocks generated by Mockito 5.4.6 from annotations
// in elevate_ecommerce_app/test/domin/use_cases/register_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:elevate_ecommerce_app/api/models/requestes/login_requests/login_request.dart'
    as _i9;
import 'package:elevate_ecommerce_app/core/api_result/api_result.dart' as _i4;
import 'package:elevate_ecommerce_app/domin/entities/login_entity.dart' as _i8;
import 'package:elevate_ecommerce_app/domin/entities/register_entity.dart'
    as _i5;
import 'package:elevate_ecommerce_app/domin/entities/requests/register_request_entity.dart'
    as _i6;
import 'package:elevate_ecommerce_app/domin/repositories/auth_repo.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AuthRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepo extends _i1.Mock implements _i2.AuthRepo {
  MockAuthRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<_i5.RegisterEntity>> register(
    _i6.RegisterRequestEntity? registerRequestEntity,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#register, [registerRequestEntity]),
            returnValue: _i3.Future<_i4.ApiResult<_i5.RegisterEntity>>.value(
              _i7.dummyValue<_i4.ApiResult<_i5.RegisterEntity>>(
                this,
                Invocation.method(#register, [registerRequestEntity]),
              ),
            ),
          )
          as _i3.Future<_i4.ApiResult<_i5.RegisterEntity>>);

  @override
  _i3.Future<_i4.ApiResult<_i8.LoginEntity>> login({
    required _i9.LoginRequestModel? loginRequestModel,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {
              #loginRequestModel: loginRequestModel,
            }),
            returnValue: _i3.Future<_i4.ApiResult<_i8.LoginEntity>>.value(
              _i7.dummyValue<_i4.ApiResult<_i8.LoginEntity>>(
                this,
                Invocation.method(#login, [], {
                  #loginRequestModel: loginRequestModel,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.ApiResult<_i8.LoginEntity>>);

  @override
  _i3.Future<void> guestUserLogin() =>
      (super.noSuchMethod(
            Invocation.method(#guestUserLogin, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> getUserStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getUserStatus, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}
