// Mocks generated by Mockito 5.4.6 from annotations
// in elevate_ecommerce_app/test/domin/use_cases/register_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:elevate_ecommerce_app/api/models/requestes/login_requests/login_request.dart'
    as _i6;
import 'package:elevate_ecommerce_app/core/api_result/api_result.dart' as _i4;
import 'package:elevate_ecommerce_app/domin/entities/auth/request/forget_password_request_entity.dart'
    as _i11;
import 'package:elevate_ecommerce_app/domin/entities/auth/request/reset_password_request_entity.dart'
    as _i15;
import 'package:elevate_ecommerce_app/domin/entities/auth/request/verify_reset_request_entity.dart'
    as _i13;
import 'package:elevate_ecommerce_app/domin/entities/auth/response/forget_password_entity.dart'
    as _i10;
import 'package:elevate_ecommerce_app/domin/entities/auth/response/reset_password_entity.dart'
    as _i14;
import 'package:elevate_ecommerce_app/domin/entities/auth/response/verify_reset_entity.dart'
    as _i12;
import 'package:elevate_ecommerce_app/domin/entities/login_entity.dart' as _i5;
import 'package:elevate_ecommerce_app/domin/entities/register_entity.dart'
    as _i8;
import 'package:elevate_ecommerce_app/domin/entities/requests/register_request_entity.dart'
    as _i9;
import 'package:elevate_ecommerce_app/domin/repositories/auth_repo.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AuthRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepo extends _i1.Mock implements _i2.AuthRepo {
  MockAuthRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<_i5.LoginEntity>> login({
    required _i6.LoginRequestModel? loginRequestModel,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {
              #loginRequestModel: loginRequestModel,
            }),
            returnValue: _i3.Future<_i4.ApiResult<_i5.LoginEntity>>.value(
              _i7.dummyValue<_i4.ApiResult<_i5.LoginEntity>>(
                this,
                Invocation.method(#login, [], {
                  #loginRequestModel: loginRequestModel,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.ApiResult<_i5.LoginEntity>>);

  @override
  _i3.Future<_i4.ApiResult<_i8.RegisterEntity>> register(
    _i9.RegisterRequestEntity? registerRequestEntity,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#register, [registerRequestEntity]),
            returnValue: _i3.Future<_i4.ApiResult<_i8.RegisterEntity>>.value(
              _i7.dummyValue<_i4.ApiResult<_i8.RegisterEntity>>(
                this,
                Invocation.method(#register, [registerRequestEntity]),
              ),
            ),
          )
          as _i3.Future<_i4.ApiResult<_i8.RegisterEntity>>);

  @override
  _i3.Future<void> guestUserLogin() =>
      (super.noSuchMethod(
            Invocation.method(#guestUserLogin, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.ApiResult<_i10.ForgetPasswordEntity>> forgetPassword(
    _i11.ForgetPasswordRequestEntity? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#forgetPassword, [request]),
            returnValue:
                _i3.Future<_i4.ApiResult<_i10.ForgetPasswordEntity>>.value(
                  _i7.dummyValue<_i4.ApiResult<_i10.ForgetPasswordEntity>>(
                    this,
                    Invocation.method(#forgetPassword, [request]),
                  ),
                ),
          )
          as _i3.Future<_i4.ApiResult<_i10.ForgetPasswordEntity>>);

  @override
  _i3.Future<_i4.ApiResult<_i12.VerifyResetEntity>> verifyResetCode(
    _i13.VerifyResetRequestEntity? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyResetCode, [request]),
            returnValue:
                _i3.Future<_i4.ApiResult<_i12.VerifyResetEntity>>.value(
                  _i7.dummyValue<_i4.ApiResult<_i12.VerifyResetEntity>>(
                    this,
                    Invocation.method(#verifyResetCode, [request]),
                  ),
                ),
          )
          as _i3.Future<_i4.ApiResult<_i12.VerifyResetEntity>>);

  @override
  _i3.Future<_i4.ApiResult<_i14.ResetPasswordEntity>> resetPassword(
    _i15.ResetPasswordRequestEntity? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [request]),
            returnValue:
                _i3.Future<_i4.ApiResult<_i14.ResetPasswordEntity>>.value(
                  _i7.dummyValue<_i4.ApiResult<_i14.ResetPasswordEntity>>(
                    this,
                    Invocation.method(#resetPassword, [request]),
                  ),
                ),
          )
          as _i3.Future<_i4.ApiResult<_i14.ResetPasswordEntity>>);
}
