// Mocks generated by Mockito 5.4.6 from annotations
// in elevate_ecommerce_app/test/api/data_source/auth_remote_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:elevate_ecommerce_app/api/client/api_client.dart' as _i5;
import 'package:elevate_ecommerce_app/api/models/requestes/add_product_to_cart_request_dto/add_product_to_cart_request_dto.dart'
    as _i7;
import 'package:elevate_ecommerce_app/api/models/requestes/login_requests/login_request.dart'
    as _i9;
import 'package:elevate_ecommerce_app/api/models/requestes/register_request_dto/register_request_dto.dart'
    as _i8;
import 'package:elevate_ecommerce_app/api/models/responses/cart_response_dto/cart_response_dto.dart'
    as _i2;
import 'package:elevate_ecommerce_app/api/models/responses/login_response/login_response_dto.dart'
    as _i4;
import 'package:elevate_ecommerce_app/api/models/responses/register_response_dto/register_response_dto.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCartResponseDto_0 extends _i1.SmartFake
    implements _i2.CartResponseDto {
  _FakeCartResponseDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRegisterResponseDto_1 extends _i1.SmartFake
    implements _i3.RegisterResponseDto {
  _FakeRegisterResponseDto_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLoginResponseDto_2 extends _i1.SmartFake
    implements _i4.LoginResponseDto {
  _FakeLoginResponseDto_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i5.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.CartResponseDto> getLoggedUserCart() =>
      (super.noSuchMethod(
            Invocation.method(#getLoggedUserCart, []),
            returnValue: _i6.Future<_i2.CartResponseDto>.value(
              _FakeCartResponseDto_0(
                this,
                Invocation.method(#getLoggedUserCart, []),
              ),
            ),
          )
          as _i6.Future<_i2.CartResponseDto>);

  @override
  _i6.Future<_i2.CartResponseDto> addProductToCart(
    _i7.AddProductToCartRequestDto? addProductToCartRequestDto,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addProductToCart, [addProductToCartRequestDto]),
            returnValue: _i6.Future<_i2.CartResponseDto>.value(
              _FakeCartResponseDto_0(
                this,
                Invocation.method(#addProductToCart, [
                  addProductToCartRequestDto,
                ]),
              ),
            ),
          )
          as _i6.Future<_i2.CartResponseDto>);

  @override
  _i6.Future<_i2.CartResponseDto> deleteSpecificCartItem(String? productId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSpecificCartItem, [productId]),
            returnValue: _i6.Future<_i2.CartResponseDto>.value(
              _FakeCartResponseDto_0(
                this,
                Invocation.method(#deleteSpecificCartItem, [productId]),
              ),
            ),
          )
          as _i6.Future<_i2.CartResponseDto>);

  @override
  _i6.Future<_i2.CartResponseDto> clearUserCart() =>
      (super.noSuchMethod(
            Invocation.method(#clearUserCart, []),
            returnValue: _i6.Future<_i2.CartResponseDto>.value(
              _FakeCartResponseDto_0(
                this,
                Invocation.method(#clearUserCart, []),
              ),
            ),
          )
          as _i6.Future<_i2.CartResponseDto>);

  @override
  _i6.Future<_i3.RegisterResponseDto> register(
    _i8.RegisterRequestDto? registerRequestDto,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#register, [registerRequestDto]),
            returnValue: _i6.Future<_i3.RegisterResponseDto>.value(
              _FakeRegisterResponseDto_1(
                this,
                Invocation.method(#register, [registerRequestDto]),
              ),
            ),
          )
          as _i6.Future<_i3.RegisterResponseDto>);

  @override
  _i6.Future<_i4.LoginResponseDto> login(
    _i9.LoginRequestModel? loginRequestModel,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#login, [loginRequestModel]),
            returnValue: _i6.Future<_i4.LoginResponseDto>.value(
              _FakeLoginResponseDto_2(
                this,
                Invocation.method(#login, [loginRequestModel]),
              ),
            ),
          )
          as _i6.Future<_i4.LoginResponseDto>);
}
